name: Run tests

on:
  push:
    branches: ["main"]

  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: ["main"]

jobs:
  tests:
    name: Install deps and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
